// SELECT_ATHLETE
export const GET_ALL_ATHLETES_FROM_GROUP = 'GET_ALL_ATHLETES_FROM_GROUP';
export const GET_ALL_ATHLETES_FROM_GROUP_SUCCESS = 'GET_ALL_ATHLETES_FROM_GROUP_SUCCESS';
export const GET_ALL_ATHLETES_FROM_GROUP_FAIL = 'GET_ALL_ATHLETES_FROM_GROUP_FAIL';
