// SIGN_UP
export const SIGN_UP_SENDING_DATA = 'SIGN_UP_SENDING_DATA';
export const SIGN_UP_SENDING_ATHLETE_IMAGE = 'SIGN_UP_SENDING_ATHLETE_IMAGE';
export const SIGN_UP_SENDING_GROUP_IMAGE = 'SIGN_UP_SENDING_GROUP_IMAGE';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';
