// SIGN_UP
export const SIGN_UP_SENDING_DATA = 'SIGN_UP_SENDING_DATA';
export const SIGN_UP_SENDING_ATHLETE_IMAGE = 'SIGN_UP_SENDING_ATHLETE_IMAGE';
export const SIGN_UP_SENDING_GROUP_IMAGE = 'SIGN_UP_SENDING_GROUP_IMAGE';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';

export const GET_GROUP_LIST = 'GET_GROUP_LIST';
export const GET_GROUP_LIST_SUCCESS = 'GET_GROUP_LIST_SUCCESS';
export const GET_GROUP_LIST_FAIL = 'GET_GROUP_LIST_FAIL';
