// PLANNING_DETAILS
export const GET_ALL_PLANNINGS_FROM_ATHLETE = 'GET_ALL_PLANNINGS_FROM_ATHLETE';
export const GET_ALL_PLANNINGS_FROM_ATHLETE_SUCCESS = 'GET_ALL_PLANNINGS_FROM_ATHLETE_SUCCESS';
export const GET_ALL_PLANNINGS_FROM_ATHLETE_FAIL = 'GET_ALL_PLANNINGS_FROM_ATHLETE_FAIL';
